### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by veD-tnayrB** [virag-ky/Youtube-Clone#1]
![image](https://user-images.githubusercontent.com/90587911/152643954-be4dfe0c-d8b1-435a-9c4b-97b3191dd349.png)
![image](https://user-images.githubusercontent.com/90587911/152643986-fef1b15e-1f0c-45fc-965c-756d6dd3f358.png)

The responsive system of the page fails in devices with medium screen and for some reason in large also
I think if I could fix it would be a good practice for you.

- Bryant

**Comment by virag-ky** [comment]
Yes, sure. I don't have much experience in this, so if you could help I will appreciate it.

**Comment by veD-tnayrB** [comment]
Sure!, I'm going to try not to modify the code too much, I'm just going to make it responsive

**Comment by virag-ky** [comment]
Okay, thanks so much.

**Comment by veD-tnayrB** [comment]
This should be solved

**Comment by virag-ky** [comment]
Great, thanks for the help out.
